server:
  servlet:
    contextPath: /api
  port: 8081
spring:
  datasource:
    continue-on-error: true
    initialization-mode: always
    initialize: true
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/students

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    exchange: amq.direct
    studentqueue: student-queue
    validationqueue: validation-queue
    studentrouting: student-routing-key
    validationrouting: validation-routing-key
    responsequeue: validation-response-queue
    responserouting: validation-response-key
    searchqueue: search-queue
    searchrouting: search-routing
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8180/auth/realms/StudentRealm
#        jwk-set-uri: http://localhost:8180/auth/realms/softvision/protocol/openid-connect/certs
#keycloak:
#  auth-server-url: http://localhost:8180/auth
#  realm: StudentRealm
#  resource: login-app
#  public-client: false
#  principal-attribute: preffered_username
