server:
  servlet:
    contextPath: /api
  port: 8081
spring:
  datasource:
    continue-on-error: true
    initialization-mode: always
    initialize: true
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/students

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    exchange: amq.direct
    studentqueue: student-queue
    validationqueue: validation-queue
    studentrouting: student-routing-key
    validationrouting: validation-routing-key
    responsequeue: validation-response-queue
    responserouting: validation-response-key
    searchqueue: search-queue
    searchrouting: search-routing